"""empty message

Revision ID: 69783bd5cc99
Revises: c7d48d4a6902
Create Date: 2018-04-27 20:26:59.518118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69783bd5cc99'
down_revision = 'c7d48d4a6902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('firstname', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('lastname', sa.String(length=80), nullable=True))
    op.drop_column('user_profile', 'first_name')
    op.drop_column('user_profile', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('user_profile', 'lastname')
    op.drop_column('user_profile', 'firstname')
    # ### end Alembic commands ###
